---
title: CffParsingException
second_title: Aspose.Font for Java API Reference
description: Represents parse exception for fonts of cff format.
type: docs
weight: 22
url: /java/com.aspose.font/cffparsingexception/
---
**Inheritance:**
java.lang.Object, java.lang.Throwable, java.lang.Exception, java.lang.RuntimeException, java.lang.IllegalStateException, [com.aspose.font.FontException](../../com.aspose.font/fontexception), [com.aspose.font.CffFontException](../../com.aspose.font/cfffontexception)
```
public class CffParsingException extends CffFontException
```

Represents parse exception for fonts of cff format. The exception can be thrown in case errors during font parsing process
## Constructors

| Constructor | Description |
| --- | --- |
| [CffParsingException()](#CffParsingException--) | Initializes new  CffParsingException  object. |
| [CffParsingException(String message)](#CffParsingException-java.lang.String-) | Initializes new  CffParsingException  object. |
| [CffParsingException(String message, RuntimeException innerException)](#CffParsingException-java.lang.String-java.lang.RuntimeException-) | Initializes new  CffParsingException  object. |
### CffParsingException() {#CffParsingException--}
```
public CffParsingException()
```


Initializes new  CffParsingException  object.

### CffParsingException(String message) {#CffParsingException-java.lang.String-}
```
public CffParsingException(String message)
```


Initializes new  CffParsingException  object.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | A message that describes the error. |

### CffParsingException(String message, RuntimeException innerException) {#CffParsingException-java.lang.String-java.lang.RuntimeException-}
```
public CffParsingException(String message, RuntimeException innerException)
```


Initializes new  CffParsingException  object.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | A message that describes the error. |
| innerException | java.lang.RuntimeException | The exception that is the cause of the current exception. |

